services:
    pagbank_challenge_mysql:
        image: mysql:latest
        container_name: pagbank_challenge_mysql
        environment:
            MYSQL_DATABASE: pagbank_challenge
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: '%'
        ports:
            - 3306:3306
        volumes:
            - ../.docker/mysql:/var/lib/mysql:rw
        networks:
            - pagbank-services
networks:
    pagbank-services:
        external: true