services:
    pagbank-app:
        container_name: pagbank-app
        build:
            context: ../../
            dockerfile: Dockerfile
        env_file:
            - ../../.env.example #Em um ambiente real aqui seria um env.local sem ser commitado
        ports:
            - 8080:8080
        networks:
            - pagbank-network
            - pagbank-services
networks:
    pagbank-network:
    pagbank-services:
        external: true